import { notFound } from "next/navigation";
import { assetUrl, getClub } from "../../../lib/api";

export default async function ClubPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  let club;
  try { club = await getClub(slug); } catch { notFound(); }
  return <main className="ClubDetail">{club.image ? <section className="club-hero" style={{ backgroundImage: `url(${assetUrl(club.image)})` }}><div className="container"><h1>{club.title}</h1><a className="down-button" href="#about" aria-label="Go to club information">↓</a></div></section> : <div className="club-hero club-hero-empty" /> }<div className="container"><section id="about" className="detail-section"><h2>About</h2><div dangerouslySetInnerHTML={{ __html: club.text ?? club.description ?? "" }} /></section>{club.events?.length ? <section id="events" className="detail-section"><h2>Events</h2><div className="event-list">{club.events.map((event) => <article key={event.id}><h3>{event.title}</h3>{event.created_at && <time>{new Date(event.created_at).toLocaleDateString("en-GB")}</time>}<div dangerouslySetInnerHTML={{ __html: event.description ?? "" }} /></article>)}</div></section> : null}{(club.photo_galleries?.length || club.video_galleries?.length) ? <section id="gallery" className="detail-section"><h2>Gallery</h2><div className="GalleryList">{club.photo_galleries?.map((gallery) => <a className="gallery-card" href={`/gallery/photo/${gallery.slug}`} key={`photo-${gallery.id}`}><div className="gallery-card-pic" style={gallery.preview ? { backgroundImage: `url(${assetUrl(gallery.preview)})` } : undefined} /><div className="gallery-card-title">{gallery.title}</div></a>)}{club.video_galleries?.map((gallery) => <a className="gallery-card" href="/gallery" key={`video-${gallery.id}`}><div className="gallery-card-pic" style={gallery.preview ? { backgroundImage: `url(${assetUrl(gallery.preview)})` } : undefined} /><div className="gallery-card-title">{gallery.title}</div></a>)}</div></section> : null}</div></main>;
}
